### ISSUE TITLE
Examples from README not working, but from make in EXAMPLE dir is ok

### ISSUE THREAD

**Issue by mauriciolp** [allansp84/visualrhythm-antispoofing#1]
Hi Allan, 
Running the make inside EXAMPLE dir and the command lines within generate the Visual Rhythms correctly, but the examples in the Example section of README gives some errors and doesnt work properly. Perhaps the parameters are not right, like the path of the videos and the output.

**Comment by allansp84** [comment]
Dear Mauricio,

I added the correct path to input videos in the Example section of the README file and a function that create the directory tree from output filename before to save the extracted visual rhythm. Please, check if now it works properly.

Thank you very much in report such failure.
Bests.

**Comment by mauriciolp** [comment]
Allan,

Now it is working perfectly.
Thank you!

Kind Regards.
